version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.17.1

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-node-modules-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-node-modules-{{ checksum "yarn.lock" }}

      - run:
          name: Run tests
          command: yarn test

workflows:
  version: 2
  build:
    jobs:
      - build
